---
- name: Install Arch Linux base packages
  become: true
  pacman:
    name:
      - git
      - htop
      - bind # dig and friends: https://wiki.archlinux.org/title/Bind
      - fastfetch # System info
      - base-devel # Required for AUR packages
      - inetutils # telnet and friends: https://wiki.archlinux.org/title/Telnet
    state: present

- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: ~/tmp/yay

- name: Build and install yay
  shell:
    cmd: makepkg -si --noconfirm
    chdir: ~/tmp/yay

- name: Clean up yay build directory
  become: true
  file:
    path: ~/tmp/yay
    state: absent
