---
- name: Install Arch Linux base packages
  become: true
  pacman:
    name:
      - git
      - htop
      - bind # dig and friends: https://wiki.archlinux.org/title/Bind
      - fastfetch # System info
      - inetutils # telnet and friends: https://wiki.archlinux.org/title/Telnet
    state: present 