- name: Install Debian/Ubuntu base packages
  become: true
  apt:
    name:
      - ansible
      - curl
      - git
      - htop
      - masscan
      - nmap
      - traceroute
      - tree
      - vim
      - whois
