---
- name: Set up Arch Linux localhost
  hosts: localhost
  connection: local

  tasks:
    - name: Install Arch Linux base packages
      become: true
      pacman:
        name:
          - git
          - zsh
          - htop
          - bind # DNS resolver
          - fastfetch # System info
        state: present

  roles:
    - arch_wsl # ONLY if running on WSL
    - oh_my_zsh
    - git
    - gh
    - vim
  #   - tmux
  #   - terraform
  #   - azure_cli
  #   - 1password_wsl
