---
- name: Set up Arch Linux localhost
  hosts: localhost
  connection: local

  tasks:
    - name: Install base packages
      become: true
      pacman:
        name:
          - bind # DNS resolver
          - git
          - zsh
          - htop
          - fastfetch
        state: present
        update_cache: true

  # roles:
  #   - oh_my_zsh
  #   - git
  #   - gh
  #   - vim
  #   - tmux
  #   - terraform
  #   - azure_cli
  #   - 1password_wsl
    # - asdf
    # - prometheus
    # - grafana
    # - node_exporter
