---
- name: Check if asdf is installed
  ansible.builtin.command: "which asdf"
  register: asdf_installed
  failed_when: false
  changed_when: false

- name: Install asdf prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - git
      - curl
      - build-essential
      - libffi-dev
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
    state: present
  when: asdf_installed.rc != 0

- name: Clone the asdf repo
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.asdf'
    version: 'v0.15.0'
    clone: true
    update: true
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  when: asdf_installed.rc != 0

- name: Add asdf initialization to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.zshrc"
    regexp: '.*asdf\.sh.*'
    line: '. "$HOME/.asdf/asdf.sh"'
    state: present
    create: true

- name: Create symlink for .asdfrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.asdfrc"
    dest: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.asdfrc"
    state: link
    force: true
