---
- name: Install asdf and dependencies
  homebrew:
    name:
      - coreutils
      - curl
      - asdf # Should be last, the others are dependencies
    state: present

- name: Add asdf initialization to .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      if [[ "$(uname)" == "Darwin" ]]; then
        . $(brew --prefix asdf)/libexec/asdf.sh
      fi
    marker: "# {mark} ANSIBLE-ASDF-MACOS"
    state: present
    create: yes

- name: Create symlink for .asdfrc
  file:
    src: "{{ role_path }}/files/.asdfrc"
    dest: "{{ ansible_env.HOME }}/.asdfrc"
    state: link
    force: true
