---
- name: Install asdf on Debian/Ubuntu
  include_tasks: debian_ubuntu.yml
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Install asdf on macOS
  include_tasks: macos.yml
  when: ansible_facts['os_family'] in ['Darwin']
