# WSL piece is taken from here mostly: https://dev.to/d4vsanchez/use-1password-ssh-agent-in-wsl-2j6m
---
- name: Install WSL prerequisites for 1Password setup on Debian/Ubuntu
  ansible.builtin.include_tasks: debian_ubuntu.yml
  when: ansible_facts['os_family'] in ['Debian', 'Ubuntu']

- name: Install WSL prerequisites for 1Password setup on Arch Linux
  ansible.builtin.include_tasks: arch_linux.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Make ~/.1password directory
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.1password"
    state: directory
    mode: '0755'

- name: Create symlink for .agent-bridge
  ansible.builtin.file:
    src: "{{ role_path }}/files/.agent-bridge.sh"
    dest: "{{ ansible_facts.env.HOME }}/.agent-bridge.sh"
    state: link
    force: true

- name: Ensure .agent-bridge.sh is executable
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.agent-bridge.sh"
    mode: '0755'

- name: Add source command to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.zshrc"
    line: "source {{ ansible_facts.env.HOME }}/.agent-bridge.sh"
    create: true
