---
- import_playbook: playbooks/linux_packages.yml # noqa: name[play]
- import_playbook: playbooks/snap_packages.yml # noqa: name[play]
- import_playbook: playbooks/linux_services.yml # noqa: name[play]
