---
- name: Install Git
  become: true
  pacman:
    name:
    - git
    state: present

- name: Create symlink for .gitconfig
  file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link
    force: true

- name: Create symlink for .gitignore
  file:
    src: "{{ role_path }}/files/.gitignore"
    dest: "{{ ansible_env.HOME }}/.gitignore"
    state: link
    force: true
