---
- name: Install Git
  become: true
  community.general.pacman:
    name:
      - git
    state: present

- name: Create symlink for .gitconfig
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "{{ ansible_facts.env.HOME }}/.gitconfig"
    state: link
    force: true

- name: Create symlink for .gitignore
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitignore"
    dest: "{{ ansible_facts.env.HOME }}/.gitignore"
    state: link
    force: true
