---
- name: Install Git on Debian/Ubuntu
  include_tasks: debian_ubuntu.yml
  when: ansible_facts['os_family'] in ['Debian', 'Ubuntu']

- name: Install Git on macOS
  include_tasks: macos.yml
  when: ansible_facts['os_family'] in ['Darwin']

- name: Install Git on Arch Linux
  include_tasks: arch_linux.yml
  when: ansible_facts['os_family'] == 'Archlinux'
