---
- name: Install Terminator
  become: true
  ansible.builtin.apt:
    name:
      - terminator
    state: present

- name: Ensure the Terminator config dir exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config/terminator"
    state: directory
    mode: '0755'

- name: Create symlink for Terminator config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_facts.env.HOME }}/.config/terminator/config"
    state: link
    force: true
