---
pacman_packages:
  - ansible
  - arc-gtk-theme
  - bleachbit
  - chromium
  - cmatrix
  - discord
  - docker
  - docker-compose
  - dropbox
  - epiphany
  - gimp
  - htop
  - imwheel
  - keybase-bin
  - laptop-mode-tools
  - libreoffice-still
  - microsoft-edge-dev-bin
  - mtr
  - neofetch
  - net-tools
  - notion-app
  - okular
  - papirus-folders-nordic
  - pinta
  - powerline-fonts
  - remmina
  - samba
  - signal-desktop
  - simplescreenrecorder
  - slack-desktop
  - speedtest-cli
  - stellarium
  - system-config-printer # For more fine-grained management of printers.
  - teams
  - terminator
  - tex-gyre-fonts
  - tmux
  - tpm2-abrmd
  - traceroute
  - tree
  - ttf-ms-fonts
  - ulauncher
  - volantes-cursors
  - whois
  - wireshark-qt
  - yarn
  - yay
