---
- name: Set up Debian/Ubuntu desktop
  hosts: localhost

  roles:
    - debian_base # Must be first in the list
    - 1password
    - asdf
    - azure_cli
    - gh
    - ghostty
    - git
    - oh_my_zsh
    - ruby
    - signal
    - spotify
    - terminator
    - terraform
    - tmux
    - vim
    - visual_studio_code
