---
# From here: https://developer.hashicorp.com/terraform/install#linux
- name: Check if Terraform is installed
  ansible.builtin.command: terraform --version
  register: terraform_check
  failed_when: false
  changed_when: false

- name: Download HashiCorp GPG key
  become: true
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-gpg-key.asc
    mode: '0644'
  when: terraform_check.rc != 0

- name: Dearmor HashiCorp GPG key
  become: true
  ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp-gpg-key.asc
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  when: terraform_check.rc != 0

- name: Add HashiCorp repository
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    content: >-
      deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}
      signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com {{ ansible_facts['lsb']['codename'] | default('focal') }} main
    mode: '0644'
  when: terraform_check.rc != 0

- name: Update apt cache after adding HashiCorp repo
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: terraform_check.rc != 0

- name: Install Terraform
  become: true
  ansible.builtin.apt:
    name: terraform
    state: present
  when: terraform_check.rc != 0
