---
- name: Ensure hashicorp/tap is tapped
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install Terraform on macOS
  community.general.homebrew:
    name: hashicorp/tap/terraform
    state: present
