---
- name: Pihole setup
  hosts: pihole

  roles:
  - base-packages-debian
  - git
  - oh_my_zsh
  - vim
  - tmux
  - cloudflared

  tasks:

    - name: Install unattended upgrades
      become: true
      apt:
        name:
        - unattended-upgrades
        state: present

    # To avoid DNS packet size errors after started to use CF Gateway for upstream.
    - name: Configure DNS packet size, create file if doesn't exist
      become: true
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.d/99-edns.conf
        line: edns-packet-max=1232
        state: present
        create: yes
    # Respond only on interface eth0
    # - https://docs.pi-hole.net/ftldns/interfaces/?h=interface
    - name: Respond only on interface eth0 - delete old config
      become: yes
      lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        regexp: '(^local-service.*)' # "Allow only local requests"
        state: absent

    - name: Respond only on interface eth0 - set correct config
      become: yes
      lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        line: 'interface=eth0' # Respond only on interface eth0
        state: present

    - name: Restart DNS service following the change above
      become: yes
      ansible.builtin.shell: pihole restartdns

    # - name: Get pihole installer
    #   get_url:
    #     url: https://install.pi-hole.net
    #     dest: /tmp/basic-install.sh

    # - name: Install pihole
    #   become: yes
    #   command: bash /tmp/basic-install.sh

    # - name: Remove old adlists
    #   file:
    #     path: /etc/pihole/
    #     state: absent
    #   with_fileglob:
    #     - /etc/pihole

    # - name: Upload configured adlists
    #   copy:
    #     src: templates/adlists.list
    #     dest: /etc/pihole/adlists.list
    #     owner: root
    #     group: root
    #     backup: yes

    # - name: Update Gravity database
    #   shell: pihole -g -r >> /tmp/gravityupdate.log