---
- name: Set up Arch Linux localhost
  hosts: localhost
  connection: local

  roles:
    - base_arch
    - oh_my_zsh
    - git
    - gh
    - vim
    - terraform
    #   - tmux
    #   - azure_cli
    #   - 1password_wsl
