---
- name: Check if Ghostty is installed
  ansible.builtin.command: "which ghostty"
  register: ghostty_installed
  failed_when: false
  changed_when: false

- name: Download Ghostty deb file
  ansible.builtin.get_url:
    url: https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.0.1-0-ppa1/ghostty_1.0.1-0.ppa1_amd64_22.04.deb
    dest: /tmp/
  when: ghostty_installed.rc != 0

- name: Install Ghostty deb file
  become: true
  ansible.builtin.shell: "dpkg -i /tmp/ghostty*.deb"
  when: ghostty_installed.rc != 0

- name: Remove Ghostty deb file
  ansible.builtin.file:
    path: /tmp/ghostty*.deb
    state: absent
