---
- name: Install desired Pacman packages
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../lists/pacman_package_list.yml
  tasks:
    - name: Upgrade pacman
      pacman:
        upgrade: true
    - name: Install pacman packages
      pacman:
        name: "{{ pacman_packages }}"
        state: latest

- name: Clear pacman cache
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Clear Linux and AUR caches
      shell: pacman -Scc --noconfirm
