---
- name: Install desired Snap packages
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../lists/snap_package_list.yml
  tasks:
    - name: Install snaps
      community.general.snap:
        name: "{{ snap_packages }}"
        state: present

    - name: Remove snaps
      community.general.snap:
        name:
          - hey-mail
        state: absent
