---
- name: Install Vim
  become: true
  apt:
    name:
      - vim
    state: present

- name: Create symlink for .vimrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: $HOME/.vimrc
    state: link
    force: true

- name: Remove existing ~/.vim/UltiSnips directory (if it exists)
  file:
    path: "{{ ansible_env.HOME }}/.vim/UltiSnips"
    state: absent

- name: Ensure ~/.vim directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory

- name: Create symlink for .vim/UltiSnips folder
  file:
    src: "{{ role_path }}/files/.vim/UltiSnips"
    dest: "{{ ansible_env.HOME }}/.vim/UltiSnips"
    state: link
    force: true
