---
- name: Set up macOS
  hosts: localhost
  vars_files:
    - vars/mas_apps.yml
  vars:
    homebrew_taps:
      - homebrew/services  # Keep only necessary taps
      - hashicorp/tap # Terraform

  # Base roles and non-Homebrew-Apps and/or apps which require config files to be arranged
  roles:
    - geerlingguy.mac.homebrew # Ensure homebrew is installed
    - geerlingguy.mac.mas # Ensure mas is installed, install Mac App Store apps via var file
    - oh_my_zsh
    - git
    - ghostty
    - asdf
    # - powerline-fonts
    - terraform
    - tmux
    - vim

  # Homebrew apps that require no config files to be arranged
  tasks:
    - name: Install Homebrew (no-cask) apps
      community.general.homebrew:
        name:
          - awscli
          - azure-cli
          - gh
          - htop
          - tree
          - wget
        state: present

    - name: Install Homebrew cask apps
      community.general.homebrew_cask:
        name:
          - 1password
          - brave-browser
          - discord
          - easy-move-plus-resize
          - firefox
          - font-jetbrains-mono
          - flux
          - raycast
          - rectangle
          - shottr
          - signal
          - spotify
          - tidal
          - visual-studio-code
        state: present
