---
- name: Create symlink for .gemrc
  file:
    src: "{{ role_path }}/files/.gemrc"
    dest: "{{ ansible_env.HOME }}/.gemrc"
    state: link

- name: Create symlink for .rspec
  file:
    src: "{{ role_path }}/files/.rspec"
    dest: "{{ ansible_env.HOME }}/.rspec"
    state: link