---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Install Debian/Ubuntu base packages
  become: true
  apt:
    name:
      - ansible
      - curl
      - dnsutils # dig, nslookup, nsupdate
      - git
      - htop
      - masscan
      - nmap
      - traceroute
      - tree
      - vim
      - whois
